### PR TITLE
Fix #34: Redirect to lang if dialect is not found

### LINKED ISSUE #34: [Feature Request] Introduce a way to ignore regional dialects in the redirect plugin
## What problem does the feature solve?

I would like to be able to forward users with browsers that indicate user preference for a specific dialect (for example, `pt-BR` vs `pt-PT` or `de-DE` vs `de-AT`) to still be redirected to the overall language even if the specific dialect does not have a locale on my VuePress instance. I found that under some circumstance, users with certain dialect preferences are not forwarded properly otherwise. I think seeing the correct language is probably better in most cases even if the dialect does not match.

## Proposed solution

I have created a pull request which introduces the non-backwards breaking variable `fuzzyLocales`. When enabled, the redirect plugin will do another check if it cannot find any matching locale. The second attempt will ignore the regional parts of the user language preference, resulting in a redirect to the correct language even if the region is not an exact match.

### PR DESCRIPTION
**Pull request by TiEul**
**Summary**

This change means that users with browsers that send an unknow region of
a known language will still be forwarded to the correct overall language.
For example, users with a browser that sends `de-AT` as a locale
will still be forwarded to the `de-DE` locale, as the plugin will
only take the lowercase `de` into account while ignoring
the region-specific uppercase `DE` and `AT`.

**Which package does this PR involve?** (check one)

- [ ] root project
- [ ] vuepress-plugin-clean-urls
- [ ] vuepress-plugin-container
- [ ] vuepress-plugin-dehydrate
- [ ] vuepress-plugin-medium-zoom
- [ ] vuepress-plugin-named-chunks
- [ ] vuepress-plugin-nprogress
- [x] vuepress-plugin-redirect
- [ ] vuepress-plugin-smooth-scroll
- [ ] vuepress-plugin-table-of-contents
- [ ] vuepress-plugin-typescript
- [ ] vuepress-plugin-zooming
- [ ] vuepress-mergeable
- [ ] vuepress-types

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (fix)
- [x] Feature (feat)
- [ ] Performance enhancement (perf)
- [ ] Code Style (style)
- [ ] Refactor (refactor)
- [x] Docs (docs)
- [ ] Build-related changes (build)
- [ ] CI-related changes (ci)
- [ ] Testing (test)
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Other information:**

https://github.com/vuepress/vuepress-community/issues/34

### CODE REVIEW

**Comment by TiEul** [comment]
I can't wait any longer with this because it's fundamentally broken so I will just continue on a fork of vuepress-community myself. I am still happy to make a new pull request, please see the conversation in  #34.

**Comment by meteorlxy** [comment]
@TiEul 

Sorry I don't have so much time for open source projects these days.

Feel free to create your own fork and thanks for your contribution~

**Comment by TiEul** [comment]
@meteorlxy I totally understand that personal priorities shift but is there no one else from the Vue(Press) community who could potentially take over the maintenance of this package? I would consider it pretty important for VuePress and clearly there are still some issues with it that make it "less than ideal" for production.

I am a bit frustrated because I never even got a response about what was wrong with my commit which is also why I never followed-up with the issue in #44 because that would take a lot of time to prepare even though it's reliably reproducible. Again, I consider this commit more of a bug fix and I even have Google Analytics data to back up this lack of redirects for many browsers.

Anyway, my commit is still here now on a cleaned refork:

https://github.com/TiEul/vuepress-community/commit/ca5f7e3f085d96d26c42022b56957238629d5f31

**Comment by meteorlxy** [comment]
In fact, this org is NOT officially maintained by VuePress team (even though I'm a member of the them). 

> And the new [VitePress](https://github.com/vuejs/vitepress) just made me not so active on VuePress.

In addition, you must know that most open source projects can not be guaranteed, because they don't have any sponsors and cannot help their authors to make a live. Just for the open source spirit！:smile:

**Pull request closed without merging**
